spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.88:3306/java21
    username: root
    password: Abcd1234$
mybatis:
  type-aliases-package: com.turing.entity
    #扫描mapper.xml，指定所在路径
  mapper-locations: classpath:mapper/*.xml



